<?php
// gallery.php
// Memindai folder saat ini untuk file gambar dan menampilkan semua gambar dalam satu halaman (inline base64).
// Tujuan: jadikan "1 file" (halaman tunggal) yang rapi dan menghindari error server-side.

error_reporting(E_ALL);
ini_set('display_errors', 1);

$allowed_ext = ['jpg','jpeg','png','webp','gif'];
$files = [];

foreach (glob("*.*") as $f) {
    $ext = strtolower(pathinfo($f, PATHINFO_EXTENSION));
    if (in_array($ext, $allowed_ext)) {
        $files[] = $f;
    }
}

function mime_type($ext) {
    $map = [
        'jpg' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'png' => 'image/png',
        'webp' => 'image/webp',
        'gif' => 'image/gif',
    ];
    return $map[$ext] ?? 'application/octet-stream';
}

?><!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Galeri Gambar — Halaman Tunggal</title>
    <link rel="stylesheet" href="auto.css">
    <style>
        /* minimal fallback styles kalau auto.css tidak dimuat */
        body{font-family: Arial, Helvetica, sans-serif;margin:20px;background:#f7f7f7;color:#222}
        h1{font-size:1.3rem;margin-bottom:12px}
        .grid{display:flex;flex-wrap:wrap;gap:12px}
        .item{background:#fff;padding:8px;border-radius:6px;box-shadow:0 1px 4px rgba(0,0,0,.06);width:calc(25% - 12px);box-sizing:border-box}
        .item img{max-width:100%;height:auto;display:block;border-radius:4px}
        .caption{font-size:.85rem;margin-top:6px;color:#555;word-break:break-all}
        @media (max-width:900px){.item{width:calc(33.333% - 12px)}}
        @media (max-width:600px){.item{width:calc(50% - 12px)}}
    </style>
</head>
<body>
    <h1>Galeri Gambar (Halaman Tunggal)</h1>
    <p>Jumlah file gambar: <?php echo count($files); ?> — file disajikan inline (base64) agar berada dalam satu dokumen.</p>
    <div class="grid">
    <?php foreach ($files as $file):
        $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
        $mime = mime_type($ext);
        $data = @file_get_contents($file);
        if ($data === false) continue;
        $b64 = base64_encode($data);
        $src = 'data:'. $mime .';base64,'. $b64;
    ?>
        <div class="item">
            <img src="<?php echo $src; ?>" alt="<?php echo htmlspecialchars($file, ENT_QUOTES); ?>">
            <div class="caption"><?php echo htmlspecialchars($file, ENT_QUOTES); ?> — <?php echo round(strlen($data)/1024,1); ?> KB</div>
        </div>
    <?php endforeach; ?>
    </div>

    <footer style="margin-top:18px;color:#666;font-size:.85rem">Generated by gallery.php — <?php echo date('Y-m-d H:i:s'); ?></footer>

</body>
</html>
